-- =============================================
-- Mise à jour branding email templates
-- Ancien: #204ce5 (bleu) → Nouveau: #EE7D07 (orange) + #0E1520 (dark)
-- Logo: "Crédit Unique" → "CRÉDIT UN1QUE"
-- =============================================

-- Header commun pour tous les templates
-- Ancien: background:#204ce5 + "Crédit Unique"
-- Nouveau: background:#0E1520 + "CRÉDIT UN1QUE" avec UN1QUE en orange

UPDATE email_templates SET corps_html = '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:20px"><div style="background:#0E1520;padding:20px;border-radius:12px 12px 0 0;text-align:center"><h1 style="color:#fff;margin:0;font-size:24px"><span style="font-weight:300">CRÉDIT</span> <span style="color:#EE7D07;font-weight:700">UN1QUE</span></h1></div><div style="background:#fff;padding:30px;border:1px solid #EBEBEB;border-top:none;border-radius:0 0 12px 12px"><p>Bonjour <strong>{{prenom}}</strong>,</p><p>Vous avez été invité(e) à accéder à votre espace de gestion de dossier sur <strong>Crédit Unique</strong>.</p><p>Pour créer votre mot de passe et accéder à vos documents, cliquez sur le bouton ci-dessous :</p><p style="text-align:center;margin:30px 0"><a href="{{lien_invitation}}" style="background:#EE7D07;color:#fff;padding:14px 28px;border-radius:8px;text-decoration:none;font-weight:bold;display:inline-block">Créer mon accès</a></p><p style="color:#585e6a;font-size:13px">Ce lien est valable 72 heures. Si vous n''avez pas demandé cet accès, ignorez cet email.</p><hr style="border:none;border-top:1px solid #EBEBEB;margin:20px 0"><p style="color:#585e6a;font-size:12px">Crédit Unique — Gestion des dossiers de rachat de crédit</p></div></div>'
WHERE slug = 'invitation_client';

UPDATE email_templates SET corps_html = '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:20px"><div style="background:#0E1520;padding:20px;border-radius:12px 12px 0 0;text-align:center"><h1 style="color:#fff;margin:0;font-size:24px"><span style="font-weight:300">CRÉDIT</span> <span style="color:#EE7D07;font-weight:700">UN1QUE</span></h1></div><div style="background:#fff;padding:30px;border:1px solid #EBEBEB;border-top:none;border-radius:0 0 12px 12px"><p>Bonjour <strong>{{prenom}}</strong>,</p><p>Le statut de votre dossier <strong>{{titre_dossier}}</strong> a été mis à jour :</p><p style="text-align:center;margin:20px 0"><span style="background:#FEF2F2;padding:6px 16px;border-radius:20px;font-size:14px">{{ancien_statut}}</span> → <span style="background:#DCFCE7;padding:6px 16px;border-radius:20px;font-size:14px;font-weight:bold">{{nouveau_statut}}</span></p><p style="text-align:center;margin:30px 0"><a href="{{lien_dossier}}" style="background:#EE7D07;color:#fff;padding:14px 28px;border-radius:8px;text-decoration:none;font-weight:bold;display:inline-block">Voir mon dossier</a></p><hr style="border:none;border-top:1px solid #EBEBEB;margin:20px 0"><p style="color:#585e6a;font-size:12px">Crédit Unique — Gestion des dossiers</p></div></div>'
WHERE slug = 'statut_change';

UPDATE email_templates SET corps_html = '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:20px"><div style="background:#0E1520;padding:20px;border-radius:12px 12px 0 0;text-align:center"><h1 style="color:#fff;margin:0;font-size:24px"><span style="font-weight:300">CRÉDIT</span> <span style="color:#EE7D07;font-weight:700">UN1QUE</span></h1></div><div style="background:#fff;padding:30px;border:1px solid #EBEBEB;border-top:none;border-radius:0 0 12px 12px"><p>Bonjour <strong>{{prenom}}</strong>,</p><p>Un nouveau document a été ajouté à votre dossier <strong>{{titre_dossier}}</strong> :</p><p style="background:#F5F5F5;padding:12px 16px;border-radius:8px;font-weight:bold">📄 {{nom_fichier}}</p><p style="text-align:center;margin:30px 0"><a href="{{lien_dossier}}" style="background:#EE7D07;color:#fff;padding:14px 28px;border-radius:8px;text-decoration:none;font-weight:bold;display:inline-block">Voir mon dossier</a></p><hr style="border:none;border-top:1px solid #EBEBEB;margin:20px 0"><p style="color:#585e6a;font-size:12px">Crédit Unique — Gestion des dossiers</p></div></div>'
WHERE slug = 'document_ajoute';

UPDATE email_templates SET corps_html = '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:20px"><div style="background:#0E1520;padding:20px;border-radius:12px 12px 0 0;text-align:center"><h1 style="color:#fff;margin:0;font-size:24px"><span style="font-weight:300">CRÉDIT</span> <span style="color:#EE7D07;font-weight:700">UN1QUE</span></h1></div><div style="background:#fff;padding:30px;border:1px solid #EBEBEB;border-top:none;border-radius:0 0 12px 12px"><p>Bonjour <strong>{{prenom}}</strong>,</p><p>Votre dossier <strong>{{titre_dossier}}</strong> est en attente de documents. Voici les pièces manquantes :</p>{{liste_documents}}<p style="text-align:center;margin:30px 0"><a href="{{lien_dossier}}" style="background:#EE7D07;color:#fff;padding:14px 28px;border-radius:8px;text-decoration:none;font-weight:bold;display:inline-block">Compléter mon dossier</a></p><hr style="border:none;border-top:1px solid #EBEBEB;margin:20px 0"><p style="color:#585e6a;font-size:12px">Crédit Unique — Gestion des dossiers</p></div></div>'
WHERE slug = 'rappel_documents';

UPDATE email_templates SET corps_html = '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:20px"><div style="background:#0E1520;padding:20px;border-radius:12px 12px 0 0;text-align:center"><h1 style="color:#fff;margin:0;font-size:24px"><span style="font-weight:300">CRÉDIT</span> <span style="color:#EE7D07;font-weight:700">UN1QUE</span></h1></div><div style="background:#fff;padding:30px;border:1px solid #EBEBEB;border-top:none;border-radius:0 0 12px 12px"><p>Bonjour <strong>{{prenom}}</strong>,</p><p>Votre compte a bien été activé sur <strong>Crédit Unique</strong>.</p><p>Vous pouvez dès maintenant accéder à votre espace pour consulter vos dossiers et transmettre vos documents.</p><p style="text-align:center;margin:30px 0"><a href="{{lien_connexion}}" style="background:#EE7D07;color:#fff;padding:14px 28px;border-radius:8px;text-decoration:none;font-weight:bold;display:inline-block">Accéder à mon espace</a></p><hr style="border:none;border-top:1px solid #EBEBEB;margin:20px 0"><p style="color:#585e6a;font-size:12px">Crédit Unique — Gestion des dossiers</p></div></div>'
WHERE slug = 'bienvenue';
